[package]
name = "bus_20240330"
version = "0.1.0"
edition = "2021"

[lints.rust]
unused = "allow"

[dependencies]
bitflags = "2.5.0"
csv = "1.3.0"
time = { version = "0.3.36", features = ["macros"] }
